version: '3.3'
services:
  front:
    image: basement-ts:latest
    container_name: udemy-ts-lesson
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/home/app
      - /home/app/node_modules
    ports:
      - ${DEV_PORT}:3000
      - ${PROD_PORT}:5000
    tty: true
